#NOTICE: This file is autogenerated by Puppet and should not be modified

 if [[ -z "$1" ]]; then
 echo "ERROR: YOU NEED TO SPECIFY A KERNEL TO BOOT!"
 exit 1
 fi

tmp=`/bin/cat /boot/grub/grub.cfg | /bin/grep menuentry | /bin/grep $1 | /bin/grep -v recovery | /bin/sed "s/menuentry '//" | sed "s/pve'.*$/pve/"`

if [[ -z "$tmp" ]]; then
 echo "ERROR: MAYBE THE KERNEL IS NOT INSTALLED?"
 exit 1
 fi

/usr/sbin/grub-set-default "$tmp"
/bin/cat /etc/default/grub | /bin/sed 's/GRUB_DEFAULT=0/GRUB_DEFAULT="saved"; GRUB_SAVEDEFAULT="true"/' > out && /bin/mv out /etc/default/grub
/usr/sbin/update-grub

exit 0
